/*
 * File: app/view/MyViewport.js
 * Date: Mon Jun 11 2012 15:00:57 GMT+0800 (SGT)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Login.view.MyViewport', {
    extend: 'Login.view.ui.MyViewport',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});