/*
 * File: app/view/MyWindow.js
 * Date: Mon Jun 11 2012 15:00:57 GMT+0800 (SGT)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext
		.define(
				'Login.view.MyWindow',
				{
					extend : 'Login.view.ui.MyWindow',

					initComponent : function() {
						var me = this;
						me.callParent(arguments);

						var btnLogin = Ext.getCmp('btnLogin');
						btnLogin.on('click', this.onLogin, this);
					},

					onLogin : function() {
						// location.href='../main.html';
						var un = this.getComponent('form').getForm().findField(
								'username').getValue();
						var pwd = this.getComponent('form').getForm()
								.findField('password').getValue();

						Ext.Ajax
								.request({
									url : '../services/account/login',
									timeout : 60000,
									method : 'get',
									params : {
										username : un,
										password : pwd
									},
									scope : this,
									success : function(response, opts) {
										var obj = Ext
												.decode(response.responseText);

										if (obj.success) {
											location.href = '../main.html';
										} else {
											Ext.Msg.alert('提示', obj.message);
//											var a = [ 'top', 'left' ], b = 0;
//											u = setInterval(
//													function() {
//														document
//																.getElementById('win').style[a[b % 2]] = (b++) % 4 < 2 ? 0
//																: 4;
//														if (b > 15) {
//															clearInterval(u);
//															b = 0;
//														}
//													}, 32);
										}

									},
									failure : function(response, opts) {
										Ext.Msg
												.alert('错误'
														+ response.status);
									}
								});

					}
				});