/*
 * File: app/view/ui/BaseViewport.js
 * Date: Mon Oct 10 2011 21:21:06 GMT+0800 (SGT)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Wanli.view.ui.BaseViewport', {
	extend : 'Ext.container.Viewport',
	id : 'baseViewport',
	layout : {type : 'border'},
	initComponent : function() {
		var me = this;
		me.items = [{
			xtype : 'panel',
			id : 'bannerpanel',
			width : 163,
			height:50,
			region : 'north',
			baseCls:"x-plain",
			html : '<div class="head_wrapper" id="headBig"><div class="head_box"><div class="logo"></div><div class="oper"><a href="###" title="退出" onclick="logout();"></a><a href="javascript: void(0);" id="headUpBtn" title="向上"></a></div><div class="user">系统管理员</div><div class="date">2013-3-20 10:30</div>	</div></div>',
		},{
			xtype : 'treepanel',
			id : 'tree',
			width : 163,
			collapsible : true,
			title : '车辆管理平台',
			store : 'DeviceJsonTreeStore',
			root : {
				text : 'Root',
				id : 'src',
				expanded : true
			},
			rootVisible : false,
			region : 'west',
			split : true,
			viewConfig : {id : 'treeView'}
		},{
			xtype : 'tabpanel',
			id : 'mainPanel',
			layout : {type : 'fit'},
			title : '',
			region : 'center',
			border : false,
			split : false
		},{
			xtype : 'panel',
			height: 25,
			layout : 'fit',
			region : 'south',
			border:false,
			baseCls:"x-plain",
			html : '<div class="foot"><span>Copyright © 2009-2013, Shpark.Net, All Rights Reserved</span></div>'
		}];
		
		me.callParent(arguments);
	}
});