/*
 * File: app/view/ui/ContentPanel.js
 * Date: Mon Oct 10 2011 21:21:06 GMT+0800 (SGT)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Wanli.view.ui.ContentPanel', {
    extend: 'Ext.panel.Panel',

    height: "100%",
    width: "100%",
    layout: {type: 'fit'},
    baseCls:"x-plain",
    headerPosition: 'left',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});