/*
 * File: app/store/DeviceJsonTreeStore.js
 * Date: Mon Oct 10 2011 21:21:06 GMT+0800 (SGT)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Wanli.store.DeviceJsonTreeStore', {
    extend: 'Ext.data.TreeStore',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'DeviceJsonTreeStore',
            proxy: {
                type: 'ajax',
                url: 'data/tree.json',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'text'
                },
                {
                    name: 'leaf'
                },
                {
                    name: 'expanded'
                },
                {
                    name: 'children'
                }
            ]
        }, cfg)]);
    }
});