/*
 * File: app/store/ComboxJsonStore.js
 * Date: Sat Dec 31 2011 01:16:46 GMT+0800 (ÖÐ¹ú±ê×¼Ê±¼ä)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Si.util.ComboxJsonStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'ComboxJsonStore',
            proxy: {
                type: 'ajax',
                url: 'dummy',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'code'
                },
                {
                    name: 'name'
                }
            ]
        }, cfg)]);
    }
});