/*
 * File: designer.js
 * Date: Wed Jun 13 2012 13:55:14 GMT+0800 (SGT)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    name: 'Login',

    launch: function() {
        Ext.QuickTips.init();

        var cmp1 = Ext.create('Login.view.MyViewport', {
            renderTo: Ext.getBody()
        });
        cmp1.show();
        var cmp2 = Ext.create('Login.view.MyWindow', {
            renderTo: Ext.getBody()
        });
        cmp2.show();
    }
});
