/*
 * File: app/view/ui/MyViewport.js
 * Date: Wed Jun 13 2012 13:55:14 GMT+0800 (SGT)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Login.view.ui.MyViewport', {
    extend: 'Ext.container.Viewport',

    style: '\'background-image: url(background.jpg);  background-repeat:repeat-x; background-color:rgb(62,170,216);',
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }
});