/*
 * File: app/view/ui/MyWindow.js
 * Date: Wed Jun 13 2012 13:55:14 GMT+0800 (SGT)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Login.view.ui.MyWindow', {
    extend: 'Ext.window.Window',

    height: 164,
    width: 300,
    id:'win',
    layout: {
        type: 'fit'
    },
    closable: false,
    title: '上海网曼车辆管理平台',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId:'form',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: '用户名',
                            fieldWidth: 50,
                            name:'username'
                        },
                        {
                            xtype: 'textfield',
                            inputType: 'password',
                            name:'password',
                            fieldLabel: '密码',
                            fieldWidth: 50
                        },
                        {
                            xtype: 'fieldcontainer',
                            height: 44,
                            layout: {
                                type: 'column'
                            },
                            fieldLabel: '验证码',
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 60
                                },
                                {
                                    xtype: 'container',
                                    height: 20,
                                    width: 80
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnLogin',
                                    text: '登陆'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }
});