/*
 * File: designer.js
 * Date: Mon Oct 10 2011 21:21:06 GMT+0800 (SGT)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    name: 'Wanli',

    stores: [
        'DeviceJsonTreeStore'
    ],

    launch: function() {
        Ext.QuickTips.init();

        var cmp1 = Ext.create('Wanli.view.BaseViewport', {
            renderTo: Ext.getBody()
        });
        cmp1.show();
        var cmp2 = Ext.create('Wanli.view.ContentPanel', {
//            renderTo: Ext.getBody()
        });
//        cmp2.show();
    }
});
