/*
 * File: designer.js Date: Mon Oct 10 2011 21:21:06 GMT+0800 (SGT)
 * 
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 * 
 * This file will be auto-generated each and everytime you export.
 * 
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
	enabled : true
});
Ext.application({
	name : 'DiskStorageApp',
	stores : [

	],

	addFormField : function(_form) {
		_form.bodyPadding = 5;
		_form.padding = "0px 0px 0px 0px";
		_form.add({
			xtype : "textfield",
			fieldLabel : 'ID',
			labelWidth : 150,
			name : 'id',
			itemId : 'id',
			align : 'center',
			anchor : '90%',
			hidden : true
		}, {
			xtype : "textfield",
			fieldLabel : '车型',
			labelWidth : 150,
			name : 'carModel',
			itemId : 'carModel',
			align : 'center',
			anchor : '90%',
			allowBlank : false,
			emptyText : '请输入车型'
		}, {
			xtype : "textfield",
			fieldLabel : '人数',
			labelWidth : 150,
			name : 'carry',
			itemId : 'carry',
			align : 'center',
			anchor : '90%',
			allowBlank : false,
			emptyText : '请输入人数'
		});
	},

	launch : function() {
		Ext.QuickTips.init();
		var cmp = Ext.create('util.BaseViewport', {
			renderTo : Ext.getBody()

		});
		cmp.initCommonUrl('CarModel');
		var me = this;
		var tb = cmp.getComponent('actionToolbar');
		// tb.getComponent('add').setVisible(false);
		// tb.getComponent('del').setVisible(false);
		// tb.getComponent('edit').setVisible(false);

		cmp.beforeAddWin = function getAddedField(_win) {
			_win.setHeight(200);
			_win.setWidth(500);

			var addForm = _win.getComponent('editForm');
			me.addFormField(addForm);
			addForm.doLayout();
			_win.doLayout();

		};

		cmp.beforeEditWin = function getAddedField(_win) {
			_win.setHeight(200);
			_win.setWidth(500);
			var editForm = _win.getComponent('editForm');
			me.addFormField(editForm);
			editForm.doLayout();
		};

		// addition button

		// cmp.searchUrl = '../services/controller/load';
		// cmp.saveUrl = '../services/controller/save';
		// cmp.editUrl = '../services/controller/save';
		// cmp.delUrl = '../services/controller/del';
		// cmp.getUrl = '../services/controller/get?id=';

		cmp.show();
		cmp.search();

	}
});
