/*
 * File: designer.js Date: Mon Oct 10 2011 21:21:06 GMT+0800 (SGT)
 * 
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 * 
 * This file will be auto-generated each and everytime you export.
 * 
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
	enabled : true
});
Ext.application({
	name : 'RoleMgmtApp',
	stores : [

	],

	addFormField : function(_form) {
		_form.bodyPadding = 5;
		_form.padding = "0px 0px 0px 0px";
		_form.add({
			xtype : "textfield",
			fieldLabel : 'ID',
			name : 'id',
			itemId : 'id',
			anchor : '90%',
			hidden : true
		}, {
			xtype : "textfield",
			fieldLabel : '角色名称',
			name : 'name',
			itemId : 'name',
			anchor : '90%',
			allowBlank : false,
			emptyText : '请输入角色名称'
		},

		{
			xtype : "textarea",
			fieldLabel : '描述',
			name : 'description',
			itemId : 'description',
			anchor : '90%',

		});

	},

	launch : function() {
		Ext.QuickTips.init();
		var cmp = Ext.create('util.BaseViewport', {
			renderTo : Ext.getBody()

		});
		
//		alert(parent.Ext.getCmp("center").getValue());
//		alert(parent.Ext.getCmp("paramshf").getValue());
		//parent window 
//		alert(parent.document);
//		if(parent.document.getElementById('childWinParams')){
////			alert(parent.document.getElementById('childWinParams').value);
//		}
		cmp.initSimpleCommonUrl('Role');
		var me = this;
		var tb = cmp.getComponent('actionToolbar');
		if(cmp.searchGrid){
			
			cmp.searchGrid.getSelectionModel().on('select',function(model, record, index) {
	            id = record.get('id');
//	            alert(id);
	        });
		}
//		var parentParams = Ext.create('Ext.form.field.Hidden', {
//			id : 'parentParams',
//			value : '',
//		});
		
//		alert(cmp.getUrlVars()['roleId']);
//		var selModel = Ext.create('Ext.selection.CheckboxModel', {
//		    checkOnly: true,
//		    listeners: {
//		        deselect: function(model, record, index) {
//		            id = record.get('id');
//		            alert(id);
//		        },
//		        select: function(model, record, index) {
//		            id = record.get('id');
//		            alert(id);
//		        }
//		    }
//		})
		// tb.getComponent('add').setVisible(false);
		// tb.getComponent('del').setVisible(false);
		// tb.getComponent('edit').setVisible(false);

		cmp.beforeAddWin = function getAddedField(_win) {
			_win.setHeight(200);
			_win.setWidth(400);

			var addForm = _win.getComponent('editForm');
			me.addFormField(addForm);
			addForm.doLayout();
			_win.doLayout();

		};

		cmp.beforeEditWin = function getAddedField(_win) {
			_win.setHeight(200);
			_win.setWidth(400);
			var editForm = _win.getComponent('editForm');
			me.addFormField(editForm);
			editForm.doLayout();
		};

		// addition button

		// cmp.searchUrl = '../services/controller/load';
		// cmp.saveUrl = '../services/controller/save';
		// cmp.editUrl = '../services/controller/save';
		// cmp.delUrl = '../services/controller/del';
		// cmp.getUrl = '../services/controller/get?id=';

		cmp.show();
		cmp.search();

	}
});
