/*
 * File: designer.js Date: Mon Oct 10 2011 21:21:06 GMT+0800 (SGT)
 * 
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 * 
 * This file will be auto-generated each and everytime you export.
 * 
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
	enabled : true
});

Ext
		.application({
			name : 'UserMgmtApp',
			stores : [

			],

			addFormField : function(_form) {

				_form.bodyPadding = 5;
				_form.padding = "0px 0px 0px 0px";
				_form.add({
					xtype : "textfield",
					fieldLabel : 'ID',
					labelWidth : 150,
					name : 'id',
					itemId : 'id',
					align : 'center',
					anchor : '90%',
					hidden : true
				}, {
					xtype : "textfield",
					fieldLabel : '用户名称',
					labelWidth : 150,
					name : 'screenName',
					itemId : 'screenName',
					align : 'center',
					anchor : '90%',
					allowBlank : false,
					emptyText : '请输入用户名称'
				}, {
					xtype : "textfield",
					fieldLabel : '姓名',
					labelWidth : 150,
					name : 'firstName',
					itemId : 'firstName',
					align : 'center',
					anchor : '90%',
					allowBlank : false,
					emptyText : '请输入姓名'
				}, {
					xtype : "textfield",
					fieldLabel : '联系电话',
					labelWidth : 150,
					name : 'name',
					itemId : 'name',
					align : 'center',
					anchor : '90%',
					allowBlank : false,
					// regex: /^\w+$/,
					// regexText:'小写字母',
					emptyText : '请输入联系电话'
				}, {
					xtype : "textfield",
					fieldLabel : 'E-MAIL',
					labelWidth : 150,
					name : 'emailAddress',
					itemId : 'emailAddress',
					align : 'center',
					anchor : '90%',
					allowBlank : false,
					// regex: /^\w+$/,
					// regexText:'小写字母',
					emptyText : '请输入电子邮件地址'
				},

				{
					xtype : 'fieldcontainer',
					labelWidth : 150,
					itemId : 'orgs',
					layout : {
						type : 'column'
					},
					fieldLabel : '用车单位',

				},

				{
					xtype : "textarea",
					fieldLabel : '备注',
					labelWidth : 150,
					name : 'note',
					itemId : 'note',
					align : 'center',
					anchor : '90%',
					height : 100

				});
				var cb = ExtjsCmp
						.createCombo('../services/org/getComboOrg?parent=null');

				var cb2 = ExtjsCmp.createCombo('../services/org/getComboOrg');
				// var cb3 = ExtjsCmp
				// .createCombo('../services/org/getComboOrg');
				// function selectOrg(combo, record, index) {
				//
				// cb2.clearValue();
				// cb3.clearValue();
				// cb2.store.load({
				// params : {
				// 'parent' : this.value
				// }
				// });
				// }

				cb.addListener('select', function(combo, record, index) {
					cb2.clearValue();
					// cb3.clearValue();
					cb2.store.load({
						params : {
							parent : this.value
						}
					});
				});

				_form.getComponent('orgs').add(cb);
				_form.getComponent('orgs').add(cb2);
				// _form.getComponent('orgs').add(cb3);

			},

			createOpenWin : function(_param) {
				if (!_param) {
					_param = '';
				}
				return Ext
						.create(
								'Ext.Window',
								{
									title : '角色列表',
									layout : 'fit',
									itemId : 'openedWin',
									height : 455,
									width : 728,
									html : '<iframe style="border-top-width: 0px; border-left-width: 0px; border-bottom-width: 0px; width: 728px; height: 455px; border-right-width: 0px" src="roleIndex.html?flag=popup'
											+ _param
											+ '" frameborder="0" width="100%" scrolling="no" height="100%"></iframe>',
								});
			},
			launch : function() {
				Ext.QuickTips.init();
				var cmp = Ext.create('util.BaseViewport', {
					renderTo : Ext.getBody()

				});
				cmp.initCommonUrl('User');
				var me = this;

				var tb = cmp.getComponent('actionToolbar');

				var operateNote = cmp.getComponent('operatePanel')
						.getComponent('operateNote');
				// tb.getComponent('add').setVisible(false);
				// tb.getComponent('del').setVisible(false);
				// tb.getComponent('edit').setVisible(false);

				cmp.beforeAddWin = function getAddedField(_win) {
					_win.setHeight(400);
					_win.setWidth(600);

					var addForm = _win.getComponent('editForm');
					me.addFormField(addForm);
					addForm.doLayout();
					_win.doLayout();

				};

				cmp.beforeEditWin = function getAddedField(_win) {
					_win.setHeight(400);
					_win.setWidth(600);
					var editForm = _win.getComponent('editForm');
					me.addFormField(editForm);
					editForm.doLayout();
				};

				cmp.afterRenderTable = function getChildData(_obj) {

				};

				var showRole = Ext.create('Ext.Button', {
					text : '查看角色',
					icon : '../image/edit.png',
					listeners : {
						click : function() {
							if (cmp.selectedGridId.length == 0) {
								Ext.Msg.alert('提示', '请选择一个用户');
								return false;
							}
							if (cmp.selectedGridId.length > 1) {
								Ext.Msg.alert('提示', '请只选择一个用户');
								return false;
							}
							var getRoleUrl = '../services/user/getRole?userId='
									+ cmp.selectedGridId[0];

							cmp.afterRenderTable = function getChildData(_obj) {

							};

							var win = Ext.create('Ext.Window', {
								title : '角色列表',
								layout : 'fit',
								itemId : 'openedWin',
								height : 450,
								width : 728,
							});
							var grid = cmp.createGrid(getRoleUrl, null, win);

						}
					}
				});

				// addition button
				var url = "../services/user/assignRole?";
				var childParams = Ext.create('Ext.form.field.Hidden', {
					id : 'paramshf',
					value : '',
					listeners : {
						click : function() {

						}

					}
				});

				childParams.on('change', function() {

					// alert("选择角色"+childParams.value);

					var roles = childParams.getValue().split(',');

					Ext.each(roles, function(role) {
						url = url + 'roleId=' + role + "&";

					});

				});

				var childParamName = Ext.create('Ext.form.field.Hidden', {
					id : 'paramsNamehf',
					value : '',
				});

				childParamName
						.on(
								'change',
								function() {

									// Ext.Msg.alert('提示', "选择角色" +
									// childParamName.value);
									if (cmp.selectedGridId.length <= 0) {

										return false;
									}
									Ext.each(cmp.selectedGridId, function(id) {
										url = url + 'userId=' + id + "&";

									});
									var msgBox = Ext
											.create(
													'Ext.window.MessageBox',
													{
														width : 300,
														height : 100,
														buttons : [
																{
																	text : '保存',
																	handler : function() {
																		Ext.Ajax
																				.request({
																					url : url,
																					scope : this,
																					method : 'GET',
																					success : function(
																							response,
																							opts) {

																						var obj = Ext
																								.decode(response.responseText);
																						Ext.Msg
																								.alert(
																										'提示',
																										obj.message);
																						msgBox
																								.close();
																					},
																					failure : function(
																							form,
																							action) {
																						Ext.Msg
																								.alert(
																										'提示',
																										'保存失败');
																						return false;
																					}
																				});

																	}
																},
																{
																	text : '取消',
																	handler : function() {
																		msgBox
																				.close();
																	}
																} ]
													});

									msgBox.show({
										title : '提示',
										msg : '当前选择角色' + childParamName.value,
										icon : Ext.Msg.QUESTION,
										modal : true,
									// fn : function(btn) {
									// console.debug('you clicked: ', btn);
									// }
									});

									operateNote.setValue(operateNote.getValue()
											+ "当前选择角色" + childParamName.value
											+ "\n");

								});

				var assignRole = Ext.create('Ext.Button', {
					text : '分配角色',
					icon : '../image/edit.png',
					listeners : {
						click : function() {
							// if(cmp.searchGrid==null){
							// Ext.Msg.alert('提示','没有需要分配角色的用户!');
							// return false;
							// }
							// var recs =
							// searchGrid.getSelectionModel().getSelection();
							// if(recs.length<=0){
							// Ext.Msg.alert('提示','请选择需要分配角色的用户!');
							// return false;
							// }

							// window.open('roleIndex.html');
							var openedWin = me.createOpenWin();
							openedWin.show();
							// cmp.searchUrl =
							// '../services/simplecommon/load?model=Role';
							//					 
							//					 
							// cmp.search();

							// var roleGrid=cmp.searchGrid;
							//					 
							// me.searchGrid = searchGrid;
							// dataPanel.add(searchGrid);
							// dataPanel.doLayout();
						}

					}
				});

				// cmp.searchUrl = '../services/controller/load';
				// cmp.saveUrl = '../services/controller/save';
				// cmp.editUrl = '../services/controller/save';
				// cmp.delUrl = '../services/controller/del';
				// cmp.getUrl = '../services/controller/get?id=';
				tb.add(assignRole);
				tb.add(showRole);
				cmp.show();
				cmp.search();

			}
		});
