/*
 * File: app/view/BaseViewport.js Date: Tue Oct 04 2011 22:44:01 GMT+0800 (SGT)
 * 
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 * 
 * This file will be generated the first time you export.
 * 
 * You should implement event handling and custom methods in this class.
 */

Ext.define('Wanli.view.BaseViewport', {
			extend : 'Wanli.view.ui.BaseViewport',
			alias : 'widget.baseViewport',

			initComponent : function() {
				var me = this;
				me.callParent(arguments);
				me.down('#tree').on('itemclick', me.onItemClick, me);
			},

			onItemClick : function(view, record, item, index, e, eOpts) {
				var title = '';
				var nodeText = record.get('text');
				var pNodeText = record.parentNode.get('text');
				var tabId = record.parentNode.get('id');
				var nodeId = record.get('id');
				if (pNodeText == 'Root') {
					title = nodeText;
				} else {
					title = nodeText + '(' + pNodeText + ')';
				}
				var mainPanel = this.down('#mainPanel');
				var url = record.raw.url;

				if (pNodeText == 'Root') {

				} else if (!mainPanel.child('#' + nodeId)) {
					var tab = Ext.widget('contentPanel', {tabId:tabId, url:url});
                    tab.id = nodeId;
                    tab.title = title;
                    tab.closable = true;
                    
					mainPanel.add(tab).show().doLayout();
				} else {
					mainPanel.setActiveTab(nodeId);
				}

			}
		});