/*
 * File: app/view/ContentPanel.js
 * Date: Tue Oct 04 2011 22:44:01 GMT+0800 (SGT)
 *
 * This file was generated by Ext Designer version 1.2.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('Wanli.view.ContentPanel', {
	extend : 'Wanli.view.ui.ContentPanel',
	alias : 'widget.contentPanel',

	initComponent : function() {
		var me = this;
		me.callParent(arguments);

		if (!me.tabId) {
			return false;
		}

		
		me.html = '<div class=""><iframe src=\'' + me.url
				+ '\' frameborder=\'0\' width=\'100%\' height=\'100%\' /></div>';
		//alert(me.url);
	}
});